

name:  Integración y entrega continua

#Evento de disparo: push
on:

  push:
    #a la rama main o ejecución manual
    branches: [ "main" ]


  workflow_dispatch:

# Cantidad de Jobs: 1

jobs:
  

  build:
    env:
      nombres: "Stephano Uriel Valentino"
      apellidos: "Correa Fernández"
      edad: "20"
    runs-on: ubuntu-latest


    steps:
      - name: presentación
        run: |
          echo "Hola, me llamo ${{ env.nombres }} ${{ env.apellidos }} y tengo ${{ env.edad }} años."
      - name: datos generales
        run: |
          echo "carrera de ingeniería de sistemas"
      - name: variables de entorne secretas
        run: |
          echo " user: ${{ secrets.USER }}"
          echo " password: ${{ secrets.PASSWORD }}"
      - name: variables abiertas
        run: |
          echo "version de proyecto: ${{ vars.VERSION_DE_MI_PROYECTO }}"